DROP DATABASE IF EXISTS BOOK_SHELF;
CREATE DATABASE BOOK_SHELF;
CHARACTER SET 'utf8'
COLLATE 'utf8_general_ci';
USE BOOK_SHELF;

CREATE TABLE BOOK(
 ISBN VARCHAR(100) NOT NULL,
 NAME VARCHAR(100) NOT NULL,
 PRICE DOUBLE NOT NULL,
 AUTHOR VARCHAR(100) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

